### ISSUE TITLE
Use system routing instead of unsafe_routes?

### ISSUE THREAD

**Issue by kaplan-michael** [slackhq/nebula#516] opened 2021-08-27 13:12 UTC
Hey I was wondering, is it possible to route using system routing eg. `ip route add` or other system equivalents?
It would be helpful for more complex routing eg. policy routing over different exit nodes. 
Thanks in advance.

**Comment by nbrownus** [comment] 2021-11-09 20:31
Closing as a dupe of #274

**Closed by nbrownus** 2021-11-09 20:31 UTC
