### ISSUE TITLE
IPV6 overlay

### ISSUE THREAD

**Issue by ddominet** [slackhq/nebula#568] opened 2021-11-05 21:53 UTC
Hi, great job guys with this project. Quick casual question. I've seen your comment, that you work on enabling IPV6 for overlay. How's the progress ?

**Comment by caguiclajmg** [comment] 2021-11-05 23:37
Dupe of #6, you can just ping there if you want to ask for progress updates

**Comment by nbrownus** [comment] 2021-11-08 18:47
Closing as a dupe of #6

**Closed by nbrownus** 2021-11-08 18:47 UTC
