### ISSUE TITLE
🐛 BUG: Wintun interface cannot be created after Windows crash ("Cannot create a file when that file already exists.")

### ISSUE THREAD

**Issue by aghand0ur** [slackhq/nebula#982] opened 2023-09-26 18:49 UTC
### What version of `nebula` are you using?

dnclient v0.2.1 (nebula v1.7.2)

### What operating system are you using?

Windows 10

### Describe the Bug

When Windows 10 crashes, DNClient does not shutdown properly.
Upon Windows reboot, the client doe snot show up in the adapter list although being running.
To run properly, I then have to manually restart the process

`Warning,26-Sep-23 1:11:03 PM,dnclient,2,None,"time=""2023-09-26T13:11:03+03:00"" level=warning msg=""Failed to initialize Nebula"" error=""failed to start nebula: create Wintun interface failed, create TUN device failed: Error creating interface: Cannot create a file when that file already exists.""`

@JohnMaguire 

### Logs from affected hosts

Adapter list after reboot from crash:
![image](https://github.com/slackhq/nebula/assets/14883982/1bfe8ce3-0d07-4997-9bfb-fa73f07b910c)

Adapter list after manual client restart:
![image](https://github.com/slackhq/nebula/assets/14883982/17b25ff8-8e7a-45a1-a49e-3d9649f0c33b)

Logs after reboot from crash:
[debug_windows.csv](https://github.com/slackhq/nebula/files/12731018/debug_windows.csv)

Logs after manual client restart:
[debug_restart.csv](https://github.com/slackhq/nebula/files/12731070/debug_restart.csv)

**Comment by JohnMaguire** [comment] 2023-09-26 19:10
I can't reproduce in a Windows 11 Pro VM. (Tested in Parallels on macOS. DNClient is in a steady state, "Actions > Stop" which immediately cuts power to the VM.)

Can you verify that you only have one DNClient service in `services.msc`? (Press Windows key, type `services.msc` and hit Enter.)

<img width="1034" alt="Screenshot 2023-09-26 at 3 08 18 PM" src="https://github.com/slackhq/nebula/assets/440033/3e7895e6-83df-4438-877e-528e75505209">

I see you're using Windows 10 so I'll try to repro there.

**Comment by JohnMaguire** [comment] 2023-09-26 19:17
@aghand0ur I see some similar issues across the web that were fixed in more recent versions of wintun.

Would you try downloading the latest wintun from https://www.wintun.net/ and replacing the contents of `C:\Program Files\Defined Networking\DNClient\dist\windows\wintun` with the contents of the downloaded ZIP folder and seeing if the issue persists?

**Comment by JohnMaguire** [comment] 2023-09-26 20:05
OK, I am able to reproduce this issue under Windows 10. I did try upgrading to the latest wintun drivers which did not appear to change anything. I suspect we'll need to do some extra cleanup here.

**Comment by aghand0ur** [comment] 2023-10-11 13:37
@JohnMaguire the PR should solve this issue I guess..
With a new release, do I need to manually update all DNClients?

**Comment by JohnMaguire** [comment] 2023-10-13 17:33
@aghand0ur Hey there, yes, you'll need to manually update all dnclients as there is no self-updating functionality today.

**Closed** 2023-10-16 15:06 UTC
Labels: NeedsFix

**Comment by aghand0ur** [comment] 2023-10-17 04:50
@JohnMaguire when is the next planned release?

**Comment by aghand0ur** [comment] 2023-10-19 05:51
Thank you @JohnMaguire
