### ISSUE TITLE
Running in Userspace, if possible?

### ISSUE THREAD

**Issue by lonnietc** [slackhq/nebula#559] opened 2021-10-26 16:41 UTC
Hi All,

I have been able to compile and run Nebula which really works well.

On thing that I would like to investigate, although I do not know if it is possible, is the possibility of running it from Userspace instead of elevated Admin and Sudo privilege's.

I know of another Start-type VPN system called SmartEther which is written in C/C++ and one it has been initially installed via elevated privilege's then it can be can be started and stopped (i.e. to make VPN connections) from userspace so that all users could do it.

Would something like this be possible with Nebula after some type of initial installation, or something?
Cheers

**Comment by rmarchei** [comment] 2021-11-22 22:41
I use a systemd script like this to run it as a non-root user:
```
# Systemd unit file for Nebula
#

[Unit]
Description=Nebula
Wants=basic.target
After=basic.target network.target
Before=sshd.service

[Service]
ExecStartPre=/usr/local/bin/nebula -test -config /etc/nebula/config.yaml
ExecStart=/usr/local/bin/nebula -config /etc/nebula/config.yaml
ExecReload=/bin/kill -HUP $MAINPID

RuntimeDirectory=nebula
ConfigurationDirectory=nebula
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
ProtectControlGroups=true
ProtectHome=true
ProtectKernelTunables=true
ProtectSystem=full
User=nebula
Group=nebula

SyslogIdentifier=nebula

Restart=always
RestartSec=2
TimeoutStopSec=5
StartLimitInterval=0
LimitNOFILE=131072

Nice=-1

[Install]
WantedBy=multi-user.target
```

**Comment by einsteinx2** [comment] 2022-05-17 17:56
Just wanted to chime in for anyone that finds this in Google search like I did to confirm that the above systemd service is working perfectly for me on Ubuntu to run as a dedicated "nebula" user instead of root.

**Comment by JohnMaguire** [comment] 2022-12-07 19:46
Thanks for all the discussion and solutions here. At this time, I'm closing this as a dupe of #300.

**Closed by JohnMaguire** 2022-12-07 19:46 UTC
