### ISSUE TITLE
Bug and feature request: Several FreeBSD-related changes (interface name, setup, clean teardown)

### ISSUE THREAD

**Issue by noseshimself** [slackhq/nebula#908] opened 2023-06-19 00:17 UTC
### What version of `nebula` are you using?

1.7.2

### What operating system are you using?

FreeBSD

### Describe the Bug

1) Bug: Nebula is leaving the tunnel interface after quitting.

1a) Bug: Nebula is terminating with an error if an interface already exists.

1b) (see 3) a renamed interface is more or less something like an alias for the interface that was renamed. So I 

2) Feature request: The "usual" way of creating tunnel interfaces on FreeBSD is creating an interface without a specific name and waiting for the number that is returned after ifconfig create (i.e. if the configuration is not specifying a tunnel interface name (or an arbitrary name Nebula should do an `ifconfig tun create`and work with the interface that is returned). This would be very useful with 

3) Permit arbitrary interface names by following interface creation with a `ifconfig tun<xxx> name <new name>`. This would be helpful in connection with software (e. g. OPNSense) that will ignore interfaces named tun*.

Right now my rc.d/ script is containing this:
```
name=`basename $0`

nebula_start()
{
  (/usr/local/nebula/bin/nebula -config $confdir/$confname 2>&1 & echo $! > ${pidfile}) | logger -t ${name} &

  logger -t ${name} "launching ${name} with PID $!"

  ifrename=${name}_rename_interface 
r  if checkyesno ${ifrename} ; then
    (
      sleep 5
      old=${name}_source_interface 
      new=${name}_target_interface
      ifconfig ${!old} name ${!new} > /dev/null
      logger -t ${name} "renaming ${!old} to ${!new}"
    ) &
  fi
}

nebula_stop()
{
  if [ -f "$pidfile" ] ; then
    kill `cat ${pidfile}`
    rm ${pidfile}
    if checkyesno ${name}_rename_interface ; then
      new=${name}_target_interface
      ifconfig ${!new} destroy
    fi
  fi
}
```

All in all I got Nebula running on OPNSense but it took several headstands and hopping through hoops to get there. Changing the way interfaces are created, torn down and how to react to interfaces already existing on startup would be helpful.

**Comment by JohnMaguire** [comment] 2023-06-20 21:04
Hi @noseshimself - this looks the same as #896 which I closed as a dupe of #309. If there's additional requirements not captured in #309, please feel free to drop them in a comment there.

I do have a PR up in #903 that does what you're asking if you want to give it a try!

**Closed by JohnMaguire** 2023-06-20 21:04 UTC
