### ISSUE TITLE
🐛 BUG: Windows Defender reports nebula-cert.exe as Wacatac.B!ml trojan

### ISSUE THREAD

**Issue by TyIsI** [slackhq/nebula#951] opened 2023-08-08 18:23 UTC
### What version of `nebula` are you using?

1.7.1

### What operating system are you using?

Wintendo

### Describe the Bug

Windows Defender detected, quarantined and reported nebula-cert.exe from the 1.7.1 release as Trojan:Win32/Wacatac.H!ml

![image](https://github.com/slackhq/nebula/assets/3118952/c401948b-6a25-48a6-9b7b-d720b4a03163)

### Logs from affected hosts

n/a

### Config files from affected hosts

n/a

**Comment by IanVS** [comment] 2023-08-09 13:52
Duplicate of https://github.com/slackhq/nebula/issues/902

**Closed by IanVS** 2023-08-09 13:52 UTC
