### ISSUE TITLE
🐛 BUG: nebula interface can come up before lighthouse hostnames are resolved

### ISSUE THREAD

**Issue by bloominstrong** [slackhq/nebula#966] opened 2023-09-04 12:44 UTC
### What version of `nebula` are you using?

1.7.2

### What operating system are you using?

Arch Linux

### Describe the Bug

When using systemd.network and routing all DNS over nebula the interface can come up before the hostname of the light house is resolved, which results in the system trying to resolve the lighthouses host name over the nebula network which it cannot connect to because it cannot resolve the lighthouse's hostname. This obvioulsy leaves DNS down for the whole system.

I say can because most of the time the interface comes up before the hostname is resolved but not every time and go is doing some level of caching so normally I reboot the whole system to test.

The issue appears to be the the DNS resolution happens in the background and so there can be a race condition, this change came in from #796 so back to 1.7.0 is affected.

Using the Pure Go or native resolver does not make a difference.
```
export GODEBUG=netdns=go    # force pure Go resolver
export GODEBUG=netdns=cgo   # force native resolver (cgo, win32)
```

The solution to this issue should be to resolver the static_host_map before the interface is created, this can be done with a simple test of adding an early net.LookupHost() in main.go as I have done below.
```
--- a/main.go
+++ b/main.go
@@ -44,6 +44,7 @@ func Main(c *config.C, configTest bool, buildVersion string, logger *logrus.Logg
                l.Println(string(b))
        }
 
+       net.LookupHost("mydomain.com")
        err := configLogger(l, c)
        if err != nil {
                return nil, util.NewContextualError("Failed to configure the logger", nil, err)
```
I have been running that on my own 1.7.2 build for ~ 2 weeks now and have not had the issue appear again

### Logs from affected hosts

```
level=error msg="DNS resolution failed for static_map host" error="lookup mydomain.com: i/o timeout" hostname=mydomain.com network=ip
```

### Config files from affected hosts

My PC Nebula config
```
static_host_map:
  "10.51.0.254": ["x.x.x.x:49153"]
  "10.51.0.5": ["mydomain.com:4242"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "10.51.0.254"
    - "10.51.0.5"

relay:
  relays:
    - "10.51.0.254"
    - "10.51.0.5"
  am_relay: false
  use_relays: true

tun:
  disabled: false
  dev: neb0
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
```

My systemd.network config
systemd 254.1-1-arch
```
Name=neb*

[Network]
DNS=10.51.0.5
Domains=~.
KeepConfiguration=yes   #Needed to allow nebula ip settings to remain
```

**Comment by JohnMaguire** [comment] 2023-09-06 16:44
Hi @bloominstrong -

If I'm understanding your issue correctly, the reproduction scenario is as follows:

* Nebula config file points to a Lighthouse server via a DNS record resolvable over public DNS
* `systemd-networkd` is configured to update the system-wide resolver to use 10.51.0.5 (an overlay IP address) once the nebula interface comes online
* Nebula uses the system-wide resolver for resolving DNS names (in your case, this points to a Nebula IP address that requires successful DNS resolution over public DNS in order to connect)

The behavior you're experiencing is:

1. Nebula starts
2. Nebula brings its adapter online, triggering systemd-networkd to reconfigure the system DNS to point to 10.51.0.5.
3. Nebula tries to handshake with 10.51.0.5 because it's defined in the `lighthouse.hosts` list
4. Nebula attempts to resolve `mydomain.com` via 10.51.0.5, which is inaccessible

Prior to Nebula v1.7.0 behavior you experienced was:

1. Nebula starts
2. Nebula tries to handshake with 10.51.0.5 because it's defined in the `lighthouse.hosts` list
3. Nebula successfully resolves `mydomain.com` via public DNS
4. Nebula brings its adapter online, triggering systemd-networkd to reconfigure the system DNS to point to 10.51.0.5.

Is that right?

#796 included a few behavior changes:

- Hostnames are now periodically re-queried. Prior to this change, DNS wasn't very useful because if the DNS name was updated, Nebula never knew about it. Therefore, Nebula needed to be restarted to learn about the new IP address. The period at which they are retried can be adjusted via the `static_map.cadence` option.
- DNS resolution no longer blocks startup
- DNS results with more than a single IP address now use all addresses instead of the first one

The behavior that broke your configuration is the lack of blocking on DNS queries. I don't think this is something we want to revert, as this is generally an improvement.

What is your goal behind using DNS for your Lighthouse? Since you are using your Lighthouse as your DNS resolver, even if you succeed at resolving the Lighthouse at startup, if its IP address changes, you won't be able to resolve it, even if you update the DNS hostname (this is the problem that led to the introduction of #796 in the first place.)

As such, my first suggestion would be to simply use an IP address for your Lighthouse. Alternatively, you may be able to configured systemd-networkd to always use a public DNS resolver for your Lighthouse domain: https://gist.github.com/brasey/fa2277a6d7242cdf4e4b7c720d42b567

**Comment by JohnMaguire** [comment] 2023-09-07 12:25
> I will add though that in the post 1.7.0 behavior that ~20% of the time that mydomain.com will resolve before systemd-networkd triggers the DNS resolver to change to 10.51.0.5, which leads me to believe a possible solution would be to move the initial DNS resolution of lighthouse.hosts earlier in the process would alleviate the issue in most cases.

Yeah, there's a race betwen a goroutine that queries for DNS and another goroutine setting up the adapter. :)

A non-blocking query is what's occurring - but you're racing between the initial query for the IP address and your systemd-networkd change kicking it.

> My use case for using DNS for my lighthouse is simply to keep my set up a bit more flexible in case the lighthouse needs to change I don't need to touch the config on every node.
> I do have multiple lighthouse's for this reason so another option could be to move the resolver to a separate node.

In any case, once you point your DNS to a Nebula node, if that node changes its IP addresses, a DNS hostname update will not be sufficient to bring your network back online (at least, any devices configured to use it for DNS.) You will need to restart each node, because they will be unable to query for the new DNS hostname.

Let me know how the systemd-networkd config change works out!

**Comment by bloominstrong** [comment] 2023-09-09 12:20
Yes using a public DNS specifically for my lighthouse domain works, for the benefit of anyone else in the future.
In ```/etc/systemd/resolved.conf``` I have set.

```
[Resolve]
DNS=1.1.1.1
Domains=~mydomain.com
```

**Comment by JohnMaguire** [comment] 2023-09-12 16:14
Thanks for confirming. Glad to hear this is working!

**Closed by JohnMaguire** 2023-09-12 16:14 UTC
Labels: WaitingForInfo
