### ISSUE TITLE
Add Lighthouse Virtual Host Support

### ISSUE THREAD

**Issue by dinooz** [slackhq/nebula#478] opened 2021-05-23 14:03 UTC
Similar to Apache & Nginx, adding Virtual Host Support will allow Handle request on Same Lighthouse IP:4242 for multiple domains/subdomains.

mylighthose.com
net1.lighthouse.com
lighthouse.other_domain.com

This will Alliow Create a Service that can work for many subdomains. perhaps with some ability of being configured via API, for portal provisioning convenience.

**Comment by caguiclajmg** [comment] 2021-05-23 17:37
I don't really get where you're going with this, if you just want to re-use a single lighthouse instance for multiple networks you can just make the lighthouse trust all the CAs from all the networks involved.

Some recent discussion here https://github.com/slackhq/nebula/issues/306#issuecomment-846474506

**Comment by dinooz** [comment] 2021-05-23 23:00
That is precisely the point, to have 1 lighthouse that serve multiple networks without trust each other.a

**Comment by caguiclajmg** [comment] 2021-05-24 00:24
Wouldn't the comment by @nbrownus in the issue I linked not work for you?

> Assuming the address spaces issued under each CA root does not overlap, you can trust each root issuing for devices at the lighthouse and re-use the single process. Just make sure to trust the root that signed the lighthouse certificate on each device.

**Comment by e-nikolov** [comment] 2021-05-26 02:01
@caguiclajmg I think one potential issue with the approach of a single lighthouse trusting all network CAs is that this way if a node from network A asks the lighthouse about the real IP of a node from network B, the lighthouse will provide it, since there is no access control built into the lighthouse as the firewalls are on node level.

This means that there could be a DDOS issue if a malicious node in one network asks the lighthouse of all real ips it knows from all networks. The only solution to this currently is to run separate lighthouses on different machines or ports, which is slightly annoying if you need to dynamically configure separate nebula networks.

**Comment by solarkraft** [comment] 2022-03-27 17:24
Honest and naive question: What are the reason a lighthouse does not trust all CAs by default? The answer to this question may be the same as for why it's not desired for a multi-user setup ...

**Comment by JohnMaguire** [comment] 2022-12-07 19:02
> Honest and naive question: What are the reasons a lighthouse does not trust all CAs by default? The answer to this question may be the same as for why it's not desired for a multi-network setup ...

I think one big reason is that if you have multiple nodes connect to the Lighthouse, claiming to be the same Nebula IP, what happens next?

**Comment by JohnMaguire** [comment] 2022-12-12 18:48
Closing as a dupe of #306.

**Closed by JohnMaguire** 2022-12-12 18:48 UTC
