### ISSUE TITLE
Route disappears after ~1 second on Synology+Docker

### ISSUE THREAD

**Issue by aaronkollasch** [slackhq/nebula#484] opened 2021-06-04 20:45 UTC
I'm running nebula in a Docker container on a Synology NAS, and there's an issue where the nebula route shows up in ``ip route`` as expected, but it disappears permanently about 1 second after the container is started, though nebula continues running. Because the route is gone, I can't connect to other nebula IPs unless I manually – or [programmatically](https://github.com/aaronkollasch/nebula/commit/240a34e383a499b4e8e8664d502ce84ea186522e) – add the route back.

I used Delve to step through [``nebula.(*Interface).activate()``](https://github.com/slackhq/nebula/blob/d13f4b5948f4191209e0bc6d350e3ea0b41c22b0/interface.go#L143), and the issue still happens. However, strangely enough, if i step slowly through [``nebula.Tun.Activate()``](https://github.com/slackhq/nebula/blob/d13f4b5948f4191209e0bc6d350e3ea0b41c22b0/tun_linux.go#L194) in tun_linux.go, the route goes up at line 253, the mtu is set at line 276, and then it never disappears.
More specifically, the route disappears if I set a breakpoint at ``/build/tun_linux.go:254`` and continue, but not at ``/build/tun_linux.go:253``.

Adding ``time.Sleep(2000*time.Millisecond)`` right before line [``253``](https://github.com/slackhq/nebula/blob/d13f4b5948f4191209e0bc6d350e3ea0b41c22b0/tun_linux.go#L253) completely fixes the problem, and the route stays up consistently (but not if I use 1500 ms).

I'm curious if anyone else has encountered this or knows why/how it could happen.

I'm running:
Synology DSM 6.2.4-25556
Synology's Docker package, version 18.09.0-0519
This [Dockerfile](https://github.com/aaronkollasch/nebula/blob/fa634f1f641db093c0781d9b863c1849dd8cf3ed/Dockerfile)
This [docker-compose.yaml](https://github.com/aaronkollasch/nebula/blob/fa634f1f641db093c0781d9b863c1849dd8cf3ed/docker-compose.yaml)
Partial config.yaml:
``` yaml
listen:
  host: "[::]"
  port: 0
punchy: true
punch_back: true
tun:
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
```

__Edit:__ I see this is related to #256 - however, I wanted to run nebula as a static binary from Docker's scratch image, so I needed a binary fix rather than a script fix. Perhaps others may find this useful as well.

**Comment by adamphetamine** [comment] 2021-09-23 05:11
you might have better success with this image-
ghcr.io/chrisx8/nebula

**Comment by JohnMaguire** [comment] 2023-07-28 17:40
Closing as a dupe of #256. Thanks for the investigation!

**Closed by JohnMaguire** 2023-07-28 17:40 UTC
