### ISSUE TITLE
DNS server should resolve lighthouse hosts 

### ISSUE THREAD

**Issue by NickHerrig** [slackhq/nebula#560] opened 2021-10-27 15:58 UTC
**Description:**
When utilizing the dns listener `serve_dns` on any number of lighthouses, it is expected that the dns listener can also resolve the lighthouse along with other hosts. 

**Expected Behavior:**
Where
- lighthouse IP is 10.0.0.1
- lighthouse name is lighthouse.mesh.example.com

```shell
>> dig @10.0.0.1 lighthouse.mesh.example.com

; <<>> DiG 9.10.6 <<>> @10.0.0.1 lighthouse.mesh.example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4452
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;lighthouse.mesh.example.com.	IN	A

;; ANSWER SECTION:
lighthouse.mesh.example.com.	3600 IN	A	10.0.0.1

;; Query time: 55 msec
;; SERVER: 10.0.0.1#53(10.0.01)
;; WHEN: Wed Oct 27 10:46:58 CDT 2021
;; MSG SIZE  rcvd: 94
```

**Current Behavior:**
```shell
>>dig @10.0.0.1 lighthouse.mesh.example.com

; <<>> DiG 9.10.6 <<>> @10.0.0.1 lighthouse.mesh.example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10146
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;lighthouse.mesh.example.com.	IN	A

;; Query time: 55 msec
;; SERVER: 10.0.0.1#53(10.0.0.1)
;; WHEN: Wed Oct 27 10:51:24 CDT 2021
;; MSG SIZE  rcvd: 46
```

**Comment by benyanke** [comment] 2021-12-13 21:58
Would love to see this as well, it causes me to need to handle some weird edge cases in the infrastructure I've built on top of nebula.

**Comment by waldner** [comment] 2022-02-23 21:18
+1

**Comment by JohnMaguire** [comment] 2022-12-07 18:30
Closing this as a dupe of #271.

**Closed by JohnMaguire** 2022-12-07 18:30 UTC
