### ISSUE TITLE
Two NAT and weird observation

### ISSUE THREAD

**Issue by thenitai** [slackhq/nebula#663] opened 2022-04-05 19:50 UTC
Hi,

I came to this project as I was testing ZeroTier and Tailscale. Both look great, but I really need something that is fast, is used in production (Slack), and doesn't include some third-party looking into our traffic.

That said, I has great success getting everything connected. Except for hosts that don't have a public IP, i.e., a private IP (either with a fixed address or per DHCP).

The weird thing is that I can see traffic in the lighthouse and when a host within another NAT pings the host in question I see a lot of traffic and handshakes and responses. No errors, but also no feedback in the shell (the one that pings).

I have pfSense running in both networks, but even with turning the firewall off, it does not work. Next, I've tried to set up a Linux Bridge and that also didn't resolve the issue. I've re-created all the certs, double-checked the IPs, made certain that the lighthouse has a public IP, etc.

Note: As soon as I give this host a public IP, it works.

Honestly not really sure what Is going on and I hope someone has a clue.

**Comment by chirayu-patel** [comment] 2022-04-06 05:17
I also have a similar observation. What has worked for me is to give public ip atleast at 1 end if both sides are NAT'ed. That surely works. 

I also have tried doing port forwarding from the router in front , but it does not work consistently.

**Comment by thenitai** [comment] 2022-04-06 16:59
Doesn't do it for me:

- Lighthouse = public IP (not behind a firewall other than local)
- Host 1 = public and private IP (pfSense DHCP and Firewall on network 1)
- Host 2 = private IP (pfSense DHCP and Firewall on network 2) <--- No access from and to others
- Host 3 = public and private IP (DigitalOcean with Firewall)

It works as soon as Host 2 gets a public IP (no other changes). No matter if the Firewall is on or off.

ZeroTier, Tailscale, and Netmaker all work with the above setup.

**Comment by bouillon** [comment] 2022-04-12 08:32
I can confirm. See #666 also

**Comment by em-winterschon** [comment] 2022-04-15 17:10
Confirmed on versions 1.3.0 and 1.5.2. I upgraded all of my hosts (18 running nebula across four datacenters) this weekend to see if that would fix the issue with the older version, but it did not. The setup has three lighthouses, one each in US-west, US-east, EU-west all with public IPs and correct firewall rules. 

All hosts behind OPnsense firewalls on physically separate subnets (at two locations) can talk to each other without issue (these talk over an OpenVPN site to site link with no firewall restrictions). Any host traffic going outside of the firewalls can ping the public VMs at various cloud providers but those same hosts cannot get traffic back into the non-cloud DCs reliably. They will work sometimes and then cease traffic entirely. 

Sometimes restarting firewalld on the cloud VMs resumes traffic but only for a short period, sometimes it fails to help at all. 

- I've tried forcing the listening IP and port for nebula as well as using `0.0.0.0` and `0` respectively, but neither makes a difference.
- I've enabled UDP NAT punching rules (static port map for UDP) at the OPNsense firewall level as mentioned in one issue/post, which did not make a difference.
- I've enabled all `punchy` aspects (punch, return, delay, punch_back) but the issue persists. 
- I've enabled all the usual trusted rules on firewalld for the cloud VMs, still the issue persists. 
- I've cleared the OPNsense firewall state tables and rebooted them to try that out, doesn't help.

So right now I've got a great internal VPN for hosts that can already talk to each other over a private LAN to begin with, and several cloud VMs which cannot get their traffic back across the nebula VPN into the datacenters. So basically nebula isn't doing its job at all. 

Like the original post mentioned, I had no issues at all with ZeroTier or TailScale, only with Nebula. For further comparison, this has not been an issue when spinning up ansible automated tunnels with Wireguard, OpenVPN, and IPsec.

**Comment by thenitai** [comment] 2022-04-18 07:09
In the meantime, we switched to OPNSense (from pfSense) but that doesn't resolve the issue either. As we couldn't wait any longer we deployed Tailscale, well Headscale to be precise (https://github.com/juanfont/headscale).

While it works, it has its own quirks. Subnets don't really work either and even with local DERP installed it can take a few seconds to connect.

**Comment by DePingus** [comment] 2022-04-21 22:19
If you're using OPNsense or PFsense have a look here: https://blog.ktz.me/punching-through-nat-with-nebula-mesh/

The reason ZeroTier works is because when ZT fails to punch through UDP, it will fall back to using the moon as a relay. Nebula doesn't have a relay mode.

**Comment by 1MachineElf** [comment] 2022-06-20 21:39
Thanks @DePingus for that link. By following the directions there for one of my networks (not LAN, but a custom "Home" network) my devices are now able to connect via their Nebula IPs while behind OPNSense.

Would someone be so kind as to put into layman's terms any potential security impact of disabling UDP port rewriting for an entire network? I'm not a network expert but I assume OPNSense wasn't configured this way by default for a good reason.

**Comment by brad-defined** [comment] 2022-07-12 13:06
Nebula 1.6.0 is released with a Relay feature, to cover cases like a Symmetric NAT.
https://github.com/slackhq/nebula/pull/678

If you don't want to change the NAT behavior of your OPNsense system, you can use relays.

Check out the example config to see how to configure a Nebula node to act as a relay, and how to configure other nodes to identify which Relay can be used by peers for access.
Also, take a look at https://github.com/slackhq/nebula/issues/33#issuecomment-1180569297 for more info on how to configure it.

**Comment by JohnMaguire** [comment] 2022-12-07 18:01
I'm closing this out for inactivity. If you continue to have issues after trying the relay feature, pleasefeel free to open up a new issue or [join us on Slack](https://join.slack.com/t/nebulaoss/shared_invite/enQtOTA5MDI4NDg3MTg4LTkwY2EwNTI4NzQyMzc0M2ZlODBjNWI3NTY1MzhiOThiMmZlZjVkMTI0NGY4YTMyNjUwMWEyNzNkZTJmYzQxOGU). Thanks!

**Closed by JohnMaguire** 2022-12-07 18:01 UTC
